
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEDIVIDE LPAREN MINUS NUM PLUS RPAREN TIMESexpression : NUM\n                  | expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expression\n                  | LPAREN expression RPAREN'
    
_lr_action_items = {'NUM':([0,3,4,5,6,7,],[2,2,2,2,2,2,]),'LPAREN':([0,3,4,5,6,7,],[3,3,3,3,3,3,]),'$end':([1,2,9,10,11,12,13,],[0,-1,-2,-3,-4,-5,-6,]),'PLUS':([1,2,8,9,10,11,12,13,],[4,-1,4,-2,-3,-4,-5,-6,]),'MINUS':([1,2,8,9,10,11,12,13,],[5,-1,5,-2,-3,-4,-5,-6,]),'TIMES':([1,2,8,9,10,11,12,13,],[6,-1,6,6,6,-4,-5,-6,]),'DIVIDE':([1,2,8,9,10,11,12,13,],[7,-1,7,7,7,-4,-5,-6,]),'RPAREN':([2,8,9,10,11,12,13,],[-1,13,-2,-3,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,4,5,6,7,],[1,8,9,10,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> NUM','expression',1,'p_expression','tryy.py',23),
  ('expression -> expression PLUS expression','expression',3,'p_expression','tryy.py',24),
  ('expression -> expression MINUS expression','expression',3,'p_expression','tryy.py',25),
  ('expression -> expression TIMES expression','expression',3,'p_expression','tryy.py',26),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression','tryy.py',27),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression','tryy.py',28),
]
